/* cmd_cannyEdge2D_host.h */

/* File autogenerated by gengetopt version 2.19.1  */

#ifndef CMD_CANNYEDGE2D_HOST_H
#define CMD_CANNYEDGE2D_HOST_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "cannyEdge2D_host"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  const char *help_help; /* Print help and exit help description.  */
  const char *version_help; /* Print version and exit help description.  */
  char * output_arg;	/* Output filename prefix (maxima chains in Xsmurf file format).  */
  char * output_orig;	/* Output filename prefix (maxima chains in Xsmurf file format) original value given at command line.  */
  const char *output_help; /* Output filename prefix (maxima chains in Xsmurf file format) help description.  */
  char * input_arg;	/* input data filename (xsmurf image format).  */
  char * input_orig;	/* input data filename (xsmurf image format) original value given at command line.  */
  const char *input_help; /* input data filename (xsmurf image format) help description.  */
  int blocksize_arg;	/* number of threads per blocks.  */
  char * blocksize_orig;	/* number of threads per blocks original value given at command line.  */
  const char *blocksize_help; /* number of threads per blocks help description.  */
  int octave_arg;	/* number of octaves.  */
  char * octave_orig;	/* number of octaves original value given at command line.  */
  const char *octave_help; /* number of octaves help description.  */
  int vox_arg;	/* number of vox per octaves.  */
  char * vox_orig;	/* number of vox per octaves original value given at command line.  */
  const char *vox_help; /* number of vox per octaves help description.  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int output_given ;	/* Whether output was given.  */
  int input_given ;	/* Whether input was given.  */
  int blocksize_given ;	/* Whether blocksize was given.  */
  int octave_given ;	/* Whether octave was given.  */
  int vox_given ;	/* Whether vox was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

extern const char *gengetopt_args_info_purpose;
extern const char *gengetopt_args_info_usage;
extern const char *gengetopt_args_info_help[];

int cmdline_parser (int argc, char * const *argv,
  struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMD_CANNYEDGE2D_HOST_H */
